<?php

namespace AppBundle\Repository;

/**
 * SubscribersHallsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscribersHallsRepository extends \Doctrine\ORM\EntityRepository
{

}
